{
    "Parameters": {
    
        "AliquotParams4": {
            "OutPlate": "pcrplate_with_cooler",
            "Solution": "fluorescein",
            "SolutionVolume": "4000ul",
            "VolumePerAliquot": "25ul",
			"Positions":[
			"A1",
			"B1",
			"C1",
			"D1"],
			"NumberofPlates":3
        }
    }
}