{
    "Parameters": {
       
        "AliquotParams3": {
            "NumberofAliquots": 8,
            "OutPlatetype": "pcrplate_with_cooler",
            "Solution": "fluorescein",
            "SolutionVolume": "4000ul",
            "VolumePerAliquot": "25ul"
        }
    }
}