{
    "Parameters": {
        "AliquotParams2": {
            "NumberofAliquots": 96,
            "OutPlate": "SRWFB96_riser20",
            "Solution": "mediaonculture",
            "SolutionVolume": "20ml",
            "VolumePerAliquot": "200ul"
        }
    }
}