{
    "Parameters": {
        "genbank": {
            "Filename": "test.gb",
            "Gene_name": "TheUnkownSequence",
            "Plasmid": false
        },
        "fasta": {
            "Filename": "test.fasta",
            "Gene_name": "TheUnkownSequence",
            "Plasmid": false
        },
        "gdx": {
            "Filename": "test.gdx",
            "Gene_name": "TheUnkownSequence",
            "Plasmid": false
        }
    }
}
