{
    "Parameters": {
        "1": {
            "MyValue": 15,
            "MyUnit": "ul"
        },
        "two": {
            "MyVolume": "15ul",
            "MyTemperature": "37C",
            "MyConc": "100ng/ul",
			"MyMoles": "0.001M",
			"MyTime":"60s",
			"MyMass":"100ng",
			"MyFlowrate":"2ml/min"
        },
        "sum": {
            "MyVolume": "15ml",
            "MyOtherVolume": "0.1l"
        },
		"SI":{
			"MyMass":"1g"
		}
    }
}
